// GENERATED by `npm run audio:gen` — do not edit by hand.
//
// Every asset (all SFX + all 9 music tracks) is a COMPRESSED MP3 inlined as a
// base64 data URI via Vite `?inline`. The runtime decodes these straight from
// base64 with decodeAudioData and ZERO fetch/network at play time.
import type { MusicTrackName, SoundEffectName } from '../sounds';
import sfxCorrect from './sfx-correct.mp3?inline';
import sfxIncorrect from './sfx-incorrect.mp3?inline';
import sfxXp from './sfx-xp.mp3?inline';
import sfxCoin from './sfx-coin.mp3?inline';
import sfxLessonComplete from './sfx-lessonComplete.mp3?inline';
import sfxSelect from './sfx-select.mp3?inline';
import sfxGameStart from './sfx-gameStart.mp3?inline';
import sfxGameOver from './sfx-gameOver.mp3?inline';
import sfxPoint from './sfx-point.mp3?inline';
import sfxJump from './sfx-jump.mp3?inline';
import sfxLand from './sfx-land.mp3?inline';
import sfxCrash from './sfx-crash.mp3?inline';
import sfxLevelUp from './sfx-levelUp.mp3?inline';
import sfxPowerup from './sfx-powerup.mp3?inline';
import sfxRotate from './sfx-rotate.mp3?inline';
import sfxClearLine from './sfx-clearLine.mp3?inline';
import sfxMove from './sfx-move.mp3?inline';
import sfxClick from './sfx-click.mp3?inline';
import sfxWin from './sfx-win.mp3?inline';
import sfxTick from './sfx-tick.mp3?inline';
import musicMenu from './music-menu.mp3?inline';
import musicRunner from './music-runner.mp3?inline';
import musicFlappy from './music-flappy.mp3?inline';
import musicSlope from './music-slope.mp3?inline';
import musicSerpent from './music-serpent.mp3?inline';
import musicPuzzle from './music-puzzle.mp3?inline';
import musicCarnival from './music-carnival.mp3?inline';
import musicTower from './music-tower.mp3?inline';
import musicPulse from './music-pulse.mp3?inline';
import musicLounge from './music-lounge.mp3?inline';

export const soundEffectAssets: Record<SoundEffectName, string> = {
  correct: sfxCorrect,
  incorrect: sfxIncorrect,
  xp: sfxXp,
  coin: sfxCoin,
  lessonComplete: sfxLessonComplete,
  select: sfxSelect,
  gameStart: sfxGameStart,
  gameOver: sfxGameOver,
  point: sfxPoint,
  jump: sfxJump,
  land: sfxLand,
  crash: sfxCrash,
  levelUp: sfxLevelUp,
  powerup: sfxPowerup,
  rotate: sfxRotate,
  clearLine: sfxClearLine,
  move: sfxMove,
  click: sfxClick,
  win: sfxWin,
  tick: sfxTick,
};

export const musicTrackAssets: Record<MusicTrackName, string> = {
  menu: musicMenu,
  runner: musicRunner,
  flappy: musicFlappy,
  slope: musicSlope,
  serpent: musicSerpent,
  puzzle: musicPuzzle,
  carnival: musicCarnival,
  tower: musicTower,
  pulse: musicPulse,
  lounge: musicLounge,
};

// Exact musical loop length (seconds) of each track, so the runtime can loop
// the precise region and skip the codec’s tiny leading/trailing padding.
export const musicTrackDurations: Record<MusicTrackName, number> = {
  menu: 19.2,
  runner: 26.88,
  flappy: 30.72,
  slope: 30.72,
  serpent: 31.68,
  puzzle: 28.8,
  carnival: 30.72,
  tower: 28.16,
  pulse: 24.96,
  lounge: 33.28,
};
