// Pre-generation script for the SlopeWise audio assets.
//
// Run via `npm run audio:gen` (vitest with vitest.audio.config.ts). Authoring it
// as a one-off Vitest case lets it run as TypeScript with the project's existing
// tooling — no extra runner/deps — and the default test glob never picks it up.
//
// It renders every recipe in `src/audio/sounds.ts` to PCM via `src/audio/synth.ts`,
// encodes each to a compressed MP3 (pure-JS `lamejs`), and writes the typed
// `index.ts` that inlines every asset as a base64 data URI (Vite `?inline`). MP3
// is ~10× smaller than WAV, so all SFX + the music tracks fit inline and the
// runtime decodes them with zero fetch/network at play time.

import { mkdirSync, readFileSync, readdirSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from 'vitest';
// `@breezystack/lamejs` is the maintained, ESM/bundler-safe fork of `lamejs`
// (the original throws `MPEGMode is not defined` under Vite). Same pure-JS MP3
// encoder API — no native deps, no network.
import { Mp3Encoder } from '@breezystack/lamejs';
import { musicTracks, soundEffects } from '../src/audio/sounds';
import { renderEffectToPcm, renderMusicLoopToPcm } from '../src/audio/synth';

// MP3 file size depends on BITRATE, not sample rate, so both render at a clean
// 22.05 kHz (less aliasing on the square/saw voices than the old 11 kHz WAVs).
// SFX get a high bitrate to keep their transients crisp; music is a quiet bed so
// a low bitrate is plenty and keeps the inlined payload small.
const SFX_SAMPLE_RATE = 22050;
const MUSIC_SAMPLE_RATE = 22050;
const SFX_BITRATE_KBPS = 128;
const MUSIC_BITRATE_KBPS = 48;

const assetsDir = resolve(dirname(fileURLToPath(import.meta.url)), '../src/audio/assets');

// The answer-feedback cues use REAL recorded samples instead of synthesis (a
// recorded "ding"/"buzzer" reads as far more satisfying than an oscillator tone;
// see src/audio/samples/NOTICE.md for sources + license). Their committed MP3s
// are copied VERBATIM, so this generator stays the single source of truth for
// `assets/` and a regenerate keeps the recordings.
const samplesDir = resolve(dirname(fileURLToPath(import.meta.url)), '../src/audio/samples');
const SAMPLED_EFFECTS: Partial<Record<string, string>> = {
  correct: 'correct-ding.mp3',
  incorrect: 'wrong-buzzer.mp3',
};

function pascal(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

// Float32 [-1, 1] → signed 16-bit PCM, the format lamejs consumes.
function floatToInt16(samples: Float32Array): Int16Array {
  const out = new Int16Array(samples.length);
  for (let i = 0; i < samples.length; i += 1) {
    const s = Math.max(-1, Math.min(1, samples[i]));
    out[i] = s < 0 ? s * 0x8000 : s * 0x7fff;
  }
  return out;
}

// Encode mono PCM to MP3 bytes with the pure-JS lamejs encoder.
function encodeMp3(samples: Float32Array, sampleRate: number, kbps: number): Uint8Array {
  const encoder = new Mp3Encoder(1, sampleRate, kbps);
  const pcm = floatToInt16(samples);
  const blockSize = 1152; // one MP3 frame worth of samples per encode call
  const chunks: Uint8Array[] = [];
  let total = 0;

  for (let i = 0; i < pcm.length; i += blockSize) {
    const encoded = encoder.encodeBuffer(pcm.subarray(i, i + blockSize));
    if (encoded.length > 0) {
      const bytes = new Uint8Array(encoded); // Int8 → Uint8 (same bytes)
      chunks.push(bytes);
      total += bytes.length;
    }
  }
  const tail = encoder.flush();
  if (tail.length > 0) {
    const bytes = new Uint8Array(tail);
    chunks.push(bytes);
    total += bytes.length;
  }

  const out = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    out.set(chunk, offset);
    offset += chunk.length;
  }
  return out;
}

// Emits the typed runtime index. Maps are typed as `Record<SoundEffectName, …>`
// / `Record<MusicTrackName, …>` so `tsc` fails loudly if any recipe is missing
// an asset (catching name drift between the contract and the generator). The
// per-track durations let the runtime loop the exact musical region, trimming
// the small leading/trailing silence the MP3 codec adds (gapless loops).
function buildIndexModule(
  effectNames: string[],
  trackNames: string[],
  durations: Record<string, number>,
): string {
  const lines: string[] = [
    '// GENERATED by `npm run audio:gen` — do not edit by hand.',
    '//',
    '// Every asset (all SFX + all 9 music tracks) is a COMPRESSED MP3 inlined as a',
    '// base64 data URI via Vite `?inline`. The runtime decodes these straight from',
    '// base64 with decodeAudioData and ZERO fetch/network at play time.',
    "import type { MusicTrackName, SoundEffectName } from '../sounds';",
  ];
  for (const name of effectNames) {
    lines.push(`import sfx${pascal(name)} from './sfx-${name}.mp3?inline';`);
  }
  for (const name of trackNames) {
    lines.push(`import music${pascal(name)} from './music-${name}.mp3?inline';`);
  }
  lines.push('');
  lines.push('export const soundEffectAssets: Record<SoundEffectName, string> = {');
  for (const name of effectNames) {
    lines.push(`  ${name}: sfx${pascal(name)},`);
  }
  lines.push('};');
  lines.push('');
  lines.push('export const musicTrackAssets: Record<MusicTrackName, string> = {');
  for (const name of trackNames) {
    lines.push(`  ${name}: music${pascal(name)},`);
  }
  lines.push('};');
  lines.push('');
  lines.push('// Exact musical loop length (seconds) of each track, so the runtime can loop');
  lines.push('// the precise region and skip the codec\u2019s tiny leading/trailing padding.');
  lines.push('export const musicTrackDurations: Record<MusicTrackName, number> = {');
  for (const name of trackNames) {
    lines.push(`  ${name}: ${Number(durations[name].toFixed(6))},`);
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

test('generate pregenerated audio assets', () => {
  mkdirSync(assetsDir, { recursive: true });

  // Remove the previous WAV assets (this generator now emits MP3 only) so no
  // stale bundled files linger in the repo.
  for (const file of readdirSync(assetsDir)) {
    if (file.endsWith('.wav')) {
      unlinkSync(resolve(assetsDir, file));
    }
  }

  const effectNames = Object.keys(soundEffects);
  const trackNames = Object.keys(musicTracks);

  let sfxBytes = 0;
  for (const name of effectNames) {
    const sample = SAMPLED_EFFECTS[name];
    // Sampled effects copy their committed recording verbatim; the rest render
    // from their recipe and encode to MP3.
    const mp3: Uint8Array = sample
      ? readFileSync(resolve(samplesDir, sample))
      : encodeMp3(
          renderEffectToPcm(soundEffects[name as keyof typeof soundEffects], SFX_SAMPLE_RATE),
          SFX_SAMPLE_RATE,
          SFX_BITRATE_KBPS,
        );
    writeFileSync(resolve(assetsDir, `sfx-${name}.mp3`), mp3);
    sfxBytes += mp3.length;
  }

  let musicBytes = 0;
  const durations: Record<string, number> = {};
  const report: string[] = [];
  for (const name of trackNames) {
    const track = musicTracks[name as keyof typeof musicTracks];

    // Every voice must span the same number of steps, or the loop would have a
    // trailing voice that drops out — catches any miscounted phrase at gen time.
    const lengths = track.voices.map((voice) => voice.notes.length);
    const steps = lengths[0];
    expect(new Set(lengths).size, `track "${name}" has uneven voice lengths: ${lengths}`).toBe(1);

    durations[name] = steps * track.stepDuration;

    const pcm = renderMusicLoopToPcm(track, MUSIC_SAMPLE_RATE);
    const mp3 = encodeMp3(pcm, MUSIC_SAMPLE_RATE, MUSIC_BITRATE_KBPS);
    const file = resolve(assetsDir, `music-${name}.mp3`);
    writeFileSync(file, mp3);

    musicBytes += mp3.length;
    report.push(
      `  music-${name}: ${durations[name].toFixed(1)}s, ${steps} steps, ${(mp3.length / 1024).toFixed(0)} KB`,
    );
  }

  writeFileSync(resolve(assetsDir, 'index.ts'), buildIndexModule(effectNames, trackNames, durations));

  // Report the inlined payload. Base64 inflates the raw MP3 bytes by ~4/3, which
  // is what actually lands in the JS bundle.
  const totalBytes = sfxBytes + musicBytes;
  const inlineBytes = Math.ceil(totalBytes / 3) * 4;
  // eslint-disable-next-line no-console
  console.log(
    `\n[audio:gen] inlined MP3 assets (${MUSIC_SAMPLE_RATE} Hz mono; music @ ${MUSIC_BITRATE_KBPS}kbps, sfx @ ${SFX_BITRATE_KBPS}kbps):\n` +
      `${report.join('\n')}\n` +
      `  sfx total:   ${(sfxBytes / 1024).toFixed(0)} KB (${effectNames.length} files)\n` +
      `  music total: ${(musicBytes / 1024).toFixed(0)} KB (${trackNames.length} files)\n` +
      `  raw total:   ${(totalBytes / 1024 / 1024).toFixed(2)} MB` +
      ` → ~${(inlineBytes / 1024 / 1024).toFixed(2)} MB inlined as base64\n`,
  );

  // Sanity: every contract name produced an asset.
  expect(effectNames).toHaveLength(20);
  expect(trackNames).toHaveLength(10);
  // Pure-JS MP3 encoding of the 10 longer tracks takes well over Vitest's default
  // 5s test timeout, so give this one-off generation plenty of headroom.
}, 120000);
